// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1NfNvqxsXoFptJRjPeeajJ1nfFsJ9uM0',
    appId: '1:181802839519:web:08295623d153ce05a1a86a',
    messagingSenderId: '181802839519',
    projectId: 'customer-support-3625f',
    authDomain: 'customer-support-3625f.firebaseapp.com',
    storageBucket: 'customer-support-3625f.appspot.com',
    measurementId: 'G-T2MK8RDVZL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_YKE5jl0Yd3z0b21CnEhZC0vEi0AHns8',
    appId: '1:181802839519:android:3d2a5b0407839fcfa1a86a',
    messagingSenderId: '181802839519',
    projectId: 'customer-support-3625f',
    storageBucket: 'customer-support-3625f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5d5ekc8Ql4ZgDDuWTX3CTZJFOTA3fRlQ',
    appId: '1:181802839519:ios:bb8c491af18f3261a1a86a',
    messagingSenderId: '181802839519',
    projectId: 'customer-support-3625f',
    storageBucket: 'customer-support-3625f.appspot.com',
    iosBundleId: 'com.example.csApp',
  );
}
